require("plugins")
require("colorscheme")
require("lsp")
require("config.telescope")
require("config.comment")
require("config.mason")
require("config.nvim-tree")
require("config.themery")
require("config.theme")
require("config.lualine")
require("config.fterm")
require("config.harpoon")
require("config.autopairs")
require("config.autotags")
require("config.conform")
-- require("config.dashboard")
require("options")
require("keymaps")
